### ISSUE TITLE
Make screencast

### ISSUE THREAD

**Issue by eddieantonio** [mdfeist/TypeV#29]
[Vissoft kinda expects it](http://vissoft16.ysu.edu/submissions.html#types).

Blocked by #28
## Tasks  (~6 hrs)
- [ ] Write a script (2 hrs)
- [ ] Do a few takes (2 hrs)
- [ ] Quick edits and upload (2 hrs)

**Comment by eddieantonio** [comment]
I put a placeholder here: https://archive.org/details/typev-demo
